"""Make term field nullable in resources

Revision ID: 22abfb071911
Revises: ecfd22c4de89
Create Date: 2025-05-04 16:59:32.471958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22abfb071911'
down_revision = 'ecfd22c4de89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
